### ISSUE TITLE
Add support for booleans?

### ISSUE THREAD

**Issue by hoboman313** [ozantunca/locally#1]
Seems like a very handy library, but where is the boolean get/set support?

**Comment by ozantunca** [comment]
Thanks for pointing that out. Boolean get/set is also supported. You can try it out at the demo page http://demo.ozantunca.org/locally/#container. It appears that I forgot to document it. I'll be fixing that

**Comment by hoboman313** [comment]
I did test it in browser ( Chrome v45 ) and booleans don't seem to be working for false values.
This is because you aren't checking the value properly for the set function.

if(!key||!value)throw new Error("Locally: no key or value given")
should be something like
if(key === undefined || value ===undefined)throw new Error("Locally: no key or value given")

**Comment by ozantunca** [comment]
I see what you mean. There is obviously a problem. I wil fix this very soon.

**Comment by hoboman313** [comment]
nice! I dig it.
